image: cirruslabs/flutter:3.32.8

pipelines:
  branches:
    main: 
      - step:
          name: Build Production APK
          caches:
            - flutter
            - gradle
          script:
            - flutter pub get
            - flutter test
            - flutter build apk --release
          artifacts:
            - build/app/outputs/flutter-apk/app-release.apk
